---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app valheim
  namespace: gameserver
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          main:
            image:
              repository: docker.io/mbround18/valheim
              tag: 3.3.0@sha256:99b1f4f90a1ff3cb95b6f4f1701afaa4fba9bed35fd614f88f885f7e647a4536
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            env:
              NAME: "Blackwater"
              PASSWORD:
                secretKeyRef:
                  name: *app
                  key: PASSWORD
              PUBLIC: 0
              TZ: "${TIMEZONE}"
              WORLD: "Blackwater"
            resources:
              requests:
                cpu: 441m
                memory: 2421Mi
              limits:
                memory: 2738Mi
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${LB_VALHEIM_IP}"
        ports:
          http:
            port: 80
          gameplay:
            enabled: true
            port: 2456
            protocol: UDP
          auth:
            enabled: true
            port: 2457
            protocol: UDP
          voip:
            enabled: true
            port: 2458
            protocol: UDP
    persistence:
      data:
        existingClaim: valheim-data
        globalMounts:
          - path: /home/steam/.config/unity3d/IronGate/Valheim/
          - path: /home/steam/valheim/
          - path: /home/steam/backups/
