---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 100
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.27.0.10101@sha256:f1a47717f5792d82becbe278c9502d756b898d63b2c637da131172c4adf1ffc7
            env:
              TZ: "${TIMEZONE}"
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 80
              RADARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 15m
                memory: 776Mi
              limits:
                memory: 813Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Radarr"
          gethomepage.dev/group: "Media Automation"
          gethomepage.dev/icon: "radarr"
          gethomepage.dev/description: "A fork of Sonarr to work with movies à la Couchpotato."
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: radarr-tls
    persistence:
      config:
        existingClaim: radarr-config-v1
      downloads:
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /zfsa/Downloads
        globalMounts:
          - path: /downloads
      media:
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /zfsa/Media
        globalMounts:
          - path: /media
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
