---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: download
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 100
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
            env:
              TZ: "${TIMEZONE}"
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &port-bt 50413
            resources:
              requests:
                cpu: 63m
                memory: 2554Mi
              limits:
                memory: 3707Mi
    service:
      main:
        nameOverride: "{{ .Release.Name }}"
        controller: main
        ports:
          http:
            port: *port
      bittorrent:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: "${LB_QBITTORRENT_IP}"
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt
    ingress:
      main:
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "qBittorrent"
          gethomepage.dev/group: "Downloaders"
          gethomepage.dev/icon: "qbittorrent"
          gethomepage.dev/description: "qBittorrent BitTorrent client."
        hosts:
          - host: &host "qb.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: qbittorrent-tls
    persistence:
      config:
        existingClaim: qbittorrent-config-v1
        globalMounts:
          - path: /config
      downloads:
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /zfsa/Downloads
        globalMounts:
          - path: /downloads
      media:
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /zfsa/Media
        globalMounts:
          - path: /media
