---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-coredns
  namespace: flux-system
spec:
  path: ./cluster/service/kubernetes/apps/kube-system/coredns/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  wait: false
