---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baikal
  namespace: collaboration
spec:
  interval: 15m
  chart:
    spec:
      interval: 15m
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/ckulka/baikal
              tag: 0.10.1-nginx-php8.2@sha256:30c099b83aa88772b683d0c09fb6fa18ac82df442349fd6342e1df576abb580c
            resources:
              requests:
                cpu: 15m
                memory: 100Mi
              limits:
                memory: 100Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Baikal"
          gethomepage.dev/group: "Collaboration"
          gethomepage.dev/icon: "baikal"
          gethomepage.dev/description: "A Calendar+Contacts server."
        hosts:
          - host: &host "baikal.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: baikal-tls
    persistence:
      data:
        existingClaim: baikal-data-v1
        globalMounts:
          - path: /var/www/baikal/Specific/
          - path: /var/www/baikal/config/
