---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: media
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 100
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/lidarr
              tag: 2.14.2.4785@sha256:b9155bf4e0939328e24b9c3748548d42aecbaf99d0391e2bb44a6768fb0d3ce9
            env:
              TZ: "${TIMEZONE}"
              LIDARR__INSTANCE_NAME: Lidarr
              LIDARR__PORT: &port 80
              LIDARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
              LIDARR__LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 15m
                memory: 309Mi
              limits:
                memory: 411Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Lidarr"
          gethomepage.dev/group: "Media Automation"
          gethomepage.dev/icon: "lidarr"
          gethomepage.dev/description: "Looks and smells like Sonarr but made for music."
        hosts:
          - host: &host "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: lidarr-tls
    persistence:
      config:
        existingClaim: lidarr-config-v1
      downloads:
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /zfsa/Downloads
        globalMounts:
          - path: /downloads
      media:
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /zfsa/Media
        globalMounts:
          - path: /media
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
