---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: fileops
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.42.5@sha256:8c9aefde747d181f024c9d7f16c363603a4f2b966518217c02354c07c47df25e
            env:
              FB_DATABASE: /config/filebrowser.db
              FB_LOG: stdout
              FB_NOAUTH: true
              FB_ROOT: /data
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 15m
                memory: 392Mi
              limits:
                memory: 392Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Filebrowser"
          gethomepage.dev/group: "FileOps"
          gethomepage.dev/icon: "filebrowser"
          gethomepage.dev/description: "Web File Browser."
        hosts:
          - host: &host "fb.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: filebrowser-tls
    persistence:
      config:
        existingClaim: filebrowser
      data:
        type: nfs
        server: "nas.${SECRET_DOMAIN}"
        path: /zfsa/Apps/External/Filebrowser
        globalMounts:
          - path: /data
